/*
 * Copyright (c) 2026 https://github.com/hairetdin
 *
 * This file is part of QORNIX project.
 * Licensed under GNU GPL v3.0 (see LICENSE file) or commercial license.
 */

#pragma once

#include <chrono>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "database/config.h"

namespace qornix_orm_tests {

class TempSqliteConfig {
public:
    explicit TempSqliteConfig(const std::string& prefix) {
        const auto now = std::chrono::steady_clock::now().time_since_epoch().count();
        const std::filesystem::path root =
            std::filesystem::temp_directory_path() / "qornix_orm_tests";
        std::filesystem::create_directories(root);

        const std::string baseName = prefix + "_" + std::to_string(now);
        dbPath_ = root / (baseName + ".sqlite");
        configPath_ = root / (baseName + ".yaml");
        dbPathString_ = dbPath_.string();
        configPathString_ = configPath_.string();

        std::ofstream config(configPath_);
        if (!config.is_open()) {
            throw std::runtime_error("Cannot create test config: " + configPath_.string());
        }

        config << "# Generated by qornix_orm test helper\n";
        config << "db:\n";
        config << "  driver: sqlite\n";
        config << "  name: " << dbPath_.string() << "\n";
        config << "  connection_string: " << dbPath_.string() << "\n";
    }

    ~TempSqliteConfig() {
        cleanup();
    }

    TempSqliteConfig(const TempSqliteConfig&) = delete;
    TempSqliteConfig& operator=(const TempSqliteConfig&) = delete;

    const std::string& configPath() const {
        return configPathString_;
    }

    const std::string& dbPath() const {
        return dbPathString_;
    }

    DatabaseConfig databaseConfig() const {
        DatabaseConfig config;
        config.dbname = dbPathString_;
        config.driver = "sqlite";
        config.connectionString = dbPathString_;
        return config;
    }

    void cleanup() {
        if (cleaned_) {
            return;
        }
        cleaned_ = true;

        const std::vector<std::filesystem::path> paths = {
            configPath_,
            dbPath_,
            std::filesystem::path(dbPath_.string() + "-wal"),
            std::filesystem::path(dbPath_.string() + "-shm")
        };

        for (const auto& path : paths) {
            std::error_code ec;
            std::filesystem::remove(path, ec);
        }
    }

private:
    std::filesystem::path dbPath_;
    std::filesystem::path configPath_;
    std::string dbPathString_;
    std::string configPathString_;
    bool cleaned_ = false;
};

} // namespace qornix_orm_tests
